version: '3.8'
services:
  ftp-server:
    image: fauria/vsftpd
    platform: linux/amd64
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ~/share:/home/vsftpd
    environment:
      FTP_USER: myuser
      FTP_PASS: mypass
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
    restart: unless-stopped