organization:
  name: "SPD"
  
clusters:
  - id: default
    name: My Local Kafka Cluster
    color: "#0013E7"
    ignoreUntrustedCertificate: false
    bootstrapServers: "$KAFKA_BOOTSTRAP_SERVER"
    properties:
    schemaRegistry:
      url: "$SR_SERVER"
      ignoreUntrustedCertificate: false
      properties:
    labels: {}

auth:
  local-users:
    - email: "joleksiysurovtsev@gmail.com"
      password: "111111"